language: swift
os: osx
osx_image: xcode12.2

before_install:
  - gem install xcpretty
  - gem install cocoapods
jobs:
  include:
    - stage: Linting
      name: SwiftLint
      addons:
        homebrew:
          packages:
          - swiftlint
          update: true
      script:
      - swiftlint
    - stage: Unit Tests
      name: iOS
      script:
      - xcodebuild -workspace "OktaLogger.xcworkspace" -scheme "OktaLoggerTests" -destination "platform=iOS Simulator,OS=latest,name=iPhone 11" clean test | xcpretty && [ ${PIPESTATUS[0]} -eq 0 ]
    - stage: Dependency Manager Validation
      name: CocoaPods
      script:
      - travis_wait 30 pod lib lint --allow-warnings
