version: 2.1

commands:
  cleanup_simulators:
    description: "Clear Simulator Caches"
    steps:
      - run:
         name: Clear Simulator caches"
         command: xcrun simctl shutdown all && xcrun simctl erase all && rm -rf ~/Library/Developer/Xcode/DerivedData && rm -rf ~/Library/Caches/com.apple.dt.Xcode && rm -rf ~/Library/Developer/Xcode/Archives && rm -rf "$(getconf DARWIN_USER_CACHE_DIR)/org.llvm.clang/ModuleCache"
  install_dependencies:
    description: "Install Dependencies"
    steps:
      - run: gem install xcpretty
      - run: gem install cocoapods
  pods:
    description: "Cocoapods install"
    steps:
      - run: pod install
  test:
    description: "Run tests"
    steps:
      - run:
         name: OktaAnalytics unit tests"
         command: set -o pipefail && xcodebuild test -workspace "OktaLogger.xcworkspace" -scheme "OktaAnalytics" -destination "platform=iOS Simulator,OS=latest,name=iPhone 14 Pro Max"
      - run:
         name: OktaSQLiteStorage unit tests"
         command: set -o pipefail && xcodebuild test -workspace "OktaLogger.xcworkspace" -scheme "OktaSQLiteStorage" -destination "platform=iOS Simulator,OS=latest,name=iPhone 14 Pro Max"
      - run:
         name: OktaLogger unit tests"
         command: set -o pipefail && xcodebuild test -workspace "OktaLogger.xcworkspace" -scheme "OktaLogger" -destination "platform=iOS Simulator,OS=latest,name=iPhone 14 Pro Max"
jobs:
  build-and-test:
    macos:
      xcode: 14.2.0
    steps:
      - cleanup_simulators
      - checkout
      - install_dependencies
      - pods
      - test

workflows:
  test:
    jobs:
      - build-and-test

