version: 2.1

commands:
  install_dependencies:
    description: "Install Dependencies"
    steps:
      - run: gem install xcpretty
      - run: gem install cocoapods
  pods:
    description: "Cocoapods install"
    steps:
      - run: pod install
  test:
    description: "Run tests"
    steps:
      - run:
         name: OktaLogger unit tests"
         command: set -o pipefail && xcodebuild -workspace "OktaLogger.xcworkspace" -scheme "OktaLogger" -destination "platform=iOS Simulator,OS=latest,name=iPhone 14"
      - run:
         name: OktaSQLiteStorage unit tests"
         command: set -o pipefail && xcodebuild -workspace "OktaLogger.xcworkspace" -scheme "OktaSQLiteStorage" -destination "platform=iOS Simulator,OS=latest,name=iPhone 14"

jobs:
  build-and-test:
    macos:
      xcode: 14.2.0
    steps:
      - checkout
      - install_dependencies
      - pods
      - test

workflows:
  test:
    jobs:
      - build-and-test

