version: 2.1

orbs:
  general-platform-helpers: okta/general-platform-helpers@1.7.6
  platform-helpers-general: atko-devices/eng-services-platform-helpers-general@1.8

commands:
  cleanup_simulators:
    description: "Clear Simulator Caches"
    steps:
      - run:
         name: Clear Simulator caches"
         command: xcrun simctl shutdown all && xcrun simctl erase all && rm -rf ~/Library/Developer/Xcode/DerivedData && rm -rf ~/Library/Caches/com.apple.dt.Xcode && rm -rf ~/Library/Developer/Xcode/Archives
  install_dependencies:
    description: "Install Dependencies"
    steps:
      - run: gem install xcpretty
      - run: gem install cocoapods
  pods:
    description: "Cocoapods install"
    steps:
      - run: pod install
  test:
    description: "Run tests"
    steps:
      - run:
         name: OktaSQLiteStorage unit tests"
         command: set -o pipefail && xcodebuild -workspace "OktaLogger.xcworkspace" -scheme "OktaSQLiteStorageTests" -destination "platform=iOS Simulator,OS=latest,name=iPhone 14 Pro Max" test
      - run:
         name: OktaLogger unit tests"
         command: set -o pipefail && xcodebuild -workspace "OktaLogger.xcworkspace" -scheme "OktaLoggerTests" -destination "platform=iOS Simulator,OS=latest,name=iPhone 14 Pro Max" test
#      - run:
#         name: OktaAnalytics unit tests"
#         command: set -o pipefail && xcodebuild -workspace "OktaLogger.xcworkspace" -scheme "OktaAnalyticsTests" -destination "platform=iOS Simulator,OS=latest,name=iPhone 14" test
jobs:
  build-and-test:
    macos:
      xcode: 14.2.0
    steps:
      - cleanup_simulators
      - checkout
      - install_dependencies
      - pods
      - test
  snyk-scan:
    docker:
      - image: cimg/openjdk:13.0
    steps:
      - attach_workspace: # Allows for sharing of build-workspace (containing downloaded dependencies) (optional)
          at: ~/project
      - platform-helpers-general/step-load-dependencies
      - run: | # Install your projects dependencies here or in the build job. Note: Here if Python.
          pip install -r requirements.txt 
      - platform-helpers-general/step-run-snyk-monitor:
          scan-all-projects: true
          skip-unresolved: false

workflows:
  semgrep:
    jobs:
      - general-platform-helpers/job-semgrep-prepare:
          name: semgrep-prepare
      - general-platform-helpers/job-semgrep-scan:
          name: semgrep-scan
          requires:
            - semgrep-prepare
  test:
    jobs:
      - build-and-test
      - platform-helpers-general/job-snyk-prepare:
          name: prepare-snyk
          requires:
            - build
      - snyk-scan:
          name: execute-snyk
          requires:
            - prepare-snyk

