version: 2.1

orbs:
  general-platform-helpers: okta/general-platform-helpers@1.8
  # platform-helpers-general: okta/eng-services-platform-helpers-general@1.8

apple-exec-common: &apple-exec-common
  macos:
    xcode: "13.4.1"

executors:
  apple-ci-x86-medium:
    <<: [ *apple-exec-common ]
    resource_class: macos.x86.medium.gen2
  apple-ci-arm-medium:
    <<: [ *apple-exec-common ]
    resource_class: macos.m1.medium.gen1
commands:
  cleanup_simulators:
    description: "Clear Simulator Caches"
    steps:
      - run:
         name: Clear Simulator caches"
         command: xcrun simctl shutdown all && xcrun simctl erase all && rm -rf ~/Library/Developer/Xcode/DerivedData && rm -rf ~/Library/Caches/com.apple.dt.Xcode && rm -rf ~/Library/Developer/Xcode/Archives
  install_dependencies:
    description: "Install Dependencies"
    steps:
      - run: gem install xcpretty
      - run: gem install cocoapods
  pods:
    description: "Cocoapods install"
    steps:
      - run: pod install
  test:
    description: "Run tests"
    steps:
      - run:
         name: OktaSQLiteStorage unit tests"
         command: set -o pipefail && xcodebuild -workspace "OktaLogger.xcworkspace" -scheme "OktaSQLiteStorageTests" -destination "platform=iOS Simulator,OS=latest,name=iPhone 14 Pro Max" test
      - run:
         name: OktaLogger unit tests"
         command: set -o pipefail && xcodebuild -workspace "OktaLogger.xcworkspace" -scheme "OktaLoggerTests" -destination "platform=iOS Simulator,OS=latest,name=iPhone 14 Pro Max" test
#      - run:
#         name: OktaAnalytics unit tests"
#         command: set -o pipefail && xcodebuild -workspace "OktaLogger.xcworkspace" -scheme "OktaAnalyticsTests" -destination "platform=iOS Simulator,OS=latest,name=iPhone 14" test
jobs:
  setup:
    executor: apple-ci-arm-medium
    steps:
      - cleanup_simulators
      - checkout
      - install_dependencies
      - pods
      - persist_to_workspace: # Allows for sharing of build-workspace (containing downloaded dependencies) (optional)
          root: ~/project
          paths:
            - .
  run_tests:
    executor: apple-ci-arm-medium
    steps:
      - attach_workspace:
          at: ~/project
      - test
  snyk-scan:
    executor: apple-ci-x86-medium
    steps:
      - attach_workspace:
        at: ~/project
      - run:
          name: run swift package show dependencies
          command: swift package show-dependencies
      - general-platform-helpers/step-load-dependencies
      - general-platform-helpers/step-run-snyk-monitor:
          scan-all-projects: true
          skip-unresolved: false
          run-on-non-main: true
          os: macos

workflows:
  semgrep:
    jobs:
      - general-platform-helpers/job-semgrep-prepare:
          name: semgrep-prepare
      - general-platform-helpers/job-semgrep-scan:
          name: semgrep-scan
          requires:
            - semgrep-prepare
  build-test:
    jobs:
      - setup
      - run_tests:
          name: tests
          requires:
            - setup
      - general-platform-helpers/job-snyk-prepare:
          name: prepare-snyk
          requires:
            - setup
      - snyk-scan:
          name: execute-snyk
          requires:
            - prepare-snyk
